d = {
    actionName: {
        KR: "기술명",
        JP: "技名",
        EN: "Action's Name",
        DE: "Fähigkeitsnamen",
        FR: "Nom de l'action",
        CN: "技能名"
    },
    general: {
        KR: "일반",
        JP: "一般",
        EN: "General",
        FR: "Général",
        DE: "Allgemeines",
        CN: "一般"
    },
    fullscreen: {
        KR: "전체 화면 모드<font class='ex'>　❙ 모바일</font>",
        JP: "フルスクリーンモード<font class='ex'>　❙ モバイル</font>",
        EN: "Fullscreen Mode<font class='ex'>　❙ Mobile</font>",
        FR: "Mode plein écran<font class='ex'>　❙ Mobile</font>",
        DE: "Vollbild Modus<font class='ex'>　❙ Handy</font>",
        CN: "全屏模式<font class='ex'>　❙ 移动端</font>",
    },
    More: {
        KR: '더보기',
        JP: 'もっと見る',
        EN: 'More',
        FR: "Plus",
        DE: 'Mehr',
        CN: "更多",
    },
    Back: {
        KR: '뒤로',
        JP: 'バック',
        EN: 'Back',
        FR: "Arrière",
        DE: 'Zurück',
        CN: "返回",
    },
    settings: {
        KR: "설정",
        JP: "設定",
        EN: "Settings",
        FR: "Paramètres",
        DE: "Einstellungen",
        CN: "设置",
    },
    Capture: {
        KR: "캡쳐<font class='ex'>　❙ PC, ACTWebSocket</font>",
        JP: "キャプチャー<font class='ex'>　❙ PC, ACTWebSocket</font>",
        EN: "Capture<font class='ex'>　❙ PC, ACTWebSocket</font>",
        FR: "Screenshot<font class='ex'>　❙ PC, ACTWebSocket</font>",
        DE: "Screenshot<font class='ex'>　❙ PC, ACTWebSocket</font>",
        CN: "截图<font class='ex'>　❙ PC, ACTWebSocket</font>",
    },
    Data: {
        KR: "데이터",
        JP: "データ",
        EN: "Data",
        FR: "Données",
        DE: "Daten",
        CN: "数据",
    },
    int: {
        KR: "정수",
        JP: "整数",
        EN: "Integer",
        FR: "Entier",
        DE: "Integer",
        CN: "整数",
    },
    float: {
        KR: "소수",
        JP: "小数",
        EN: "Decimal",
        FR: "Décimal",
        DE: "Dezimal",
        CN: "小数",
    },
    ".": {
        KR: ".",
        JP: ".",
        EN: ".",
        FR: ".",
        DE: ".",
        CN: ".",
    },
    ",": {
        KR: ",",
        JP: ",",
        EN: ",",
        FR: ",",
        DE: ",",
        CN: ",",
    },
    "_": {
        KR: "공백",
        JP: "ブランク",
        EN: "Blank",
        FR: "Espace",
        DE: "Leerzeichen",
        CN: "空白",
    },
    "'": {
        KR: "'",
        JP: "'",
        EN: "'",
        FR: "'",
        DE: "'",
        CN: "'",
    },
    noUse: {
        KR: "사용 안 함",
        JP: "使わない",
        EN: "Disable",
        FR: "Désactivé",
        DE: "Deaktivieren",
        CN: "禁用",
    },
    1: {
        KR: '1',
        JP: '1',
        EN: '1',
        FR: '1',
        DE: '1',
        CN: "1",
    },
    2: {
        KR: '2',
        JP: '2',
        EN: '2',
        FR: '2',
        DE: '2',
        CN: "2",
    },
    dpsTable: {
        KR: "DPS 테이블",
        JP: "DPSテーブル",
        EN: "DPS Table",
        FR: "Tableau DPS",
        DE: "DPS Tabelle",
        CN: "DPS 表",
    },
    hpsTable: {
        KR: "HPS 테이블",
        JP: "HPSテーブル",
        EN: "HPS Table",
        FR: "Tableau HPS",
        DE: "HPS Tabelle",
        CN: "HPS 表"
    },
    jobFilter: {
        KR: "직업 필터",
        JP: "ジョブフィルタ",
        EN: "Job Filter",
        FR: "Filtre de Job",
        DE: "Job Filter",
        CN: "职业过滤",
    },
    filter_tank: {
        KR: "방어",
        JP: "タンク",
        EN: "Tank",
        FR: "Tank",
        DE: "Verteidiger",
        CN: "防护职业",
    },
    filter_healer: {
        KR: "회복",
        JP: "ヒーラー",
        EN: "Healer",
        FR: "Soigneur",
        DE: "Heiler",
        CN: "治疗职业",
    },
    filter_DPS: {
        KR: "공격",
        JP: "DPS",
        EN: "DPS",
        FR: "DPS",
        DE: "Angreifer",
        CN: "进攻职业",
    },
    filter_CL: {
        KR: "제작자 & 채집가",
        JP: "クラフター & ギャザラー",
        EN: "Disciples of the Hand/Land",
        FR: "Disciples de la Main/Terre",
        DE: "Handwerker & Sammler",
        CN: "能工巧匠 & 大地使者",
    },
    filter_cbo: {
        KR: "초코보",
        JP: "チョコボ",
        EN: "Chocobo",
        FR: "Chocobo",
        DE: "Chocobo",
        CN: "陆行鸟",
    },
    caution_tt: {
        KR: "설정 전 주의사항",
        JP: "設定する前の注意事項",
        EN: "Read Me First",
        FR: "Lisez moi en premier",
        DE: "Erst alles genau durchlesen, dann Einstellungen vornehmen!",
        CN: "设置前的注意事项",
    },
    caution_m1: {
        KR: '<br>키보드로 직접 입력 시,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ 오버레이 관리자 ❯ 설정 ❯ <font class="ac"><b>키 입력 무시, 자동 숨기기(~~.exe)</b> 체크 해제</font> 필수입니다.',
        JP: '<br>キーボード入力の場合は,<br>ACT > Plugins > ACTWebSocket > Open Manager > Preferences ❯ <font class="ac"><b>No Focus</b>のチェークを解除</font>してください。',
        EN: '<br>When you type directly,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">UNCHEKED <b>No Focus</b></font>',
        FR: '<br>Pour saisir directement des valeurs,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">DESACTIVE <b>No Focus</b></font>',
        DE: '<br>Wenn du direkt schreiben möchtest, gehe wie folgt vor:,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">DEAKTIVIERE <b>No Focus</b></font>',
        CN: '<br>在键盘输入的情况下，<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac"><b>No Focus</b> 请取消勾选。</font>',
    },
    caution_m2: {
        KR: '<br>키보드로 직접 입력 시,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ 오버레이 관리자 ❯ 설정 ❯ <font class="ac"><b>키 입력 무시, 자동 숨기기(~~.exe)</b> 체크 해제</font> 필수입니다.<br><br><font class="ac">❖ 모바일 환경에서는 해당 기능을 지원하지 않습니다.<br>❖ 글꼴 이름만 입력합니다. (글꼴 스타일 제외)<br>❖ 글꼴 파일이 손상됐거나 글꼴 이름을 잘못 입력한 경우 기본값으로 적용합니다.</font>',
        JP: '<br>キーボード入力の場合は,<br>ACT > Plugins > ACTWebSocket > Open Manager > Preferences ❯ <font class="ac"><b>No Focus</b>のチェークを解除</font>してください。<br><br><font class="ac">❖ 携帯環境では該当オプションは使用できません。<br>❖ フォントの名前だけ入力してください。(フォントスタイル除外)<br>❖ フォントのファイルが損傷されている、もしくは名前が間違っている場合は基本フォントが適用されます。</font>',
        EN: '<br>When you type directly,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">UNCHEKED <b>No Focus</b></font><br><br><font class="ac">❖ This feature isn\'t supported in mobile environment.<br>❖ You only must be entered the font name. (EXCEPT font style)<br>❖ If the font file is corrupted or font name is entered incorrectly, it will be applied by default.</font>',
        FR: '<br>Pour saisir directement des valeurs,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">DESACTIVE <b>No Focus</b></font><br><br><font class="ac">❖ Cette fonction est indisponible pour l\'environement sur mobile.<br>❖ Vous devez seulement saisir le nom de la police. (EXCEPTE le style de police)<br>❖ Si la police est corrompue  ou que le nom est incorrect, la valeur par défaut sera appliquée.</font>',
        DE: '<br>Wenn du direkt schreiben möchtest, gehe wie folgt vor:,<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac">DEAKTIVIERE <b>No Focus</b></font><br><br><font class="ac">❖ Dieses Feature wird nicht in der mobilen Umgebung unterstützt.<br>❖ Nur den Schriftart-Namen eintragen. (AUSNAHME: Schriftstil)<br>❖ Falls die Datei der Schriftart beschädigt oder der Name falsch geschrieben ist, wird die Standard-Schriftart angewendet.</font>',
        CN: '<br>在键盘输入的情况下，<br>ACT ❯ Plugins ❯ ACTWebSocket ❯ Open Manager ❯ Preferences ❯ <font class="ac"><b>No Focus</b> 请取消勾选。</font><br><br><font class="ac">❖ 移动端不支持此功能。<br>❖ 您只能输入字体名称。 (除字体样式外)<br>❖ 如果字体文损坏或者不存在，则使用默认字体。</font>',
    },
    input_font: {
        m: {
            KR: "글꼴 이름",
            JP: "フォントの名前",
            EN: "Font Name",
            FR: "Nom de police",
            DE: "Schriftart-Namen",
            CN: "字体名字",
        },
        i: 'text_fields',
        e: 'li_text_inbtn',
        ul: 0
    },
    nav: {
        KR: "내비게이션",
        JP: "ナビゲーション",
        EN: "Navigation",
        FR: "Navigation",
        DE: "Navigationsleiste",
        CN: "导航",
    },
    navBg: {
        KR: "배경",
        JP: "背景",
        EN: "Background",
        FR: "Arrière plan",
        DE: "Hintergrund",
        CN: "背景",
    },
    pattern: {
        KR: "패턴",
        JP: "パターン",
        EN: "Pattern",
        FR: "Modèle",
        DE: "Muster",
        CN: "图案",
    },
    edge: {
        KR: "테두리",
        JP: "枠線",
        EN: "Border",
        FR: "Bordure",
        DE: "Rand",
        CN: "边框",
    },
    jobIcon: {
        KR: "아이콘<font class='ex'>　❙ 클래스 또는 직업</font>",
        JP: "アイコン<font class='ex'>　❙ クラスもしくはジョブ</font>",
        EN: "Icon<font class='ex'>　❙ Class or Job</font>",
        FR: "Icône<font class='ex'>　❙ Classe ou Job</font>",
        DE: "Symbole<font class='ex'>　❙ Klassen/Job</font>",
        CN: "图标<font class='ex'>　❙ 玩家职业图标</font>",
    },
    rps: {
        KR: "데이터",
        JP: "データ",
        EN: "Data",
        FR: "Données",
        DE: "Daten",
        CN: "数据",
    },
    table: {
        KR: "테이블",
        JP: "テーブル",
        EN: "Table",
        FR: "Tableau",
        DE: "Tabellen",
        CN: "表",
    },
    graph: {
        KR: "그래프",
        JP: "グラフ",
        EN: "Graph",
        FR: "Graphique",
        DE: "Graphen",
        CN: "图表",
    },
    time: {
        KR: "시간",
        JP: "時間",
        EN: "Time",
        FR: "Temps",
        DE: "Zeit",
        CN: "时间",
    },
    target: {
        KR: "대상",
        JP: "ターゲット",
        EN: "Target",
        FR: "Cible",
        DE: "Ziel",
        CN: "目标",
    },
    icon: {
        KR: "아이콘",
        JP: "アイコン",
        EN: "Icon",
        FR: "Icône",
        DE: "Symbole",
        CN: "图标",
    },
    header: {
        KR: "헤더",
        JP: "ヘッダー",
        EN: "Header",
        FR: "Entête",
        DE: "Kopf",
        CN: "头部",
    },
    headerText: {
        KR: "헤더 글자",
        JP: "ヘッダーテキスト",
        EN: "Header Text",
        FR: "Texte d\'entête",
        DE: "Text auf den Kopf",
        CN: "头部文字",
    },
    body: {
        KR: "바디",
        JP: "ボディ",
        EN: "Body",
        FR: "Corps",
        DE: "Hauptteil",
        CN: "主体",
    },
    line_ho: {
        KR: "구분선<font class='ex'>　❙ 가로</font>",
        JP: "区分線<font class='ex'>　❙ 横</font>",
        EN: "Division Lines<font class='ex'>　❙ Horizontal</font>",
        FR: "Ligne de séparation<font class='ex'>　❙ Horizontale</font>",
        DE: "Trennlinien<font class='ex'>　❙ Horizontal</font>",
        CN: "分界线<font class='ex'>　❙ 横</font>",
    },
    line_ve: {
        KR: "구분선<font class='ex'>　❙ 세로</font>",
        JP: "区分線<font class='ex'>　❙ 縦</font>",
        EN: "Division Lines<font class='ex'>　❙ Vertical</font>",
        FR: "Ligne de séparation<font class='ex'>　❙ Verticale</font>",
        DE: "Trennlinien<font class='ex'>　❙ Vertical</font>",
        CN: "分界线<font class='ex'>　❙ 竖</font>",
    },
    bodyYOU: {
        KR: "배경<font class='ex'>　❙ 내 캐릭터 </font>",
        JP: "背景<font class='ex'>　❙ 自分のキャラクター</font>",
        EN: "Background<font class='ex'>　❙ My Character</font>",
        FR: "Arrière plan<font class='ex'>　❙ Mon personnage</font>",
        DE: "Hintergrund<font class='ex'>　❙ Eigenen Charakter</font>",
        CN: "背景<font class='ex'>　❙ 自己角色 </font>",
    },
    bodyOther: {
        KR: "배경<font class='ex'>　❙ 타 캐릭터</font>",
        JP: "背景<font class='ex'>　❙ 他のキャラクター</font>",
        EN: "Background<font class='ex'>　❙ Other Character</font>",
        FR: "Arrière plan<font class='ex'>　❙ Autre personnage</font>",
        DE: "Hintergrund<font class='ex'>　❙ Andere Charaktere</font>",
        CN: "背景<font class='ex'>　❙ 其他角色 </font>",
    },
    itYOU: {
        KR: "아이콘, 글자<font class='ex'>　❙ 내 캐릭터</font>",
        JP: "アイコン、テキスト<font class='ex'>　❙ 自分のキャラクター</font>",
        EN: "Icon, Text<font class='ex'>　❙ My Character</font>",
        FR: "Icône, Text<font class='ex'>　❙ Mon personnage</font>",
        DE: "Symbole, Text<font class='ex'>　❙ Eigenen Charakter</font>",
        CN: "图标，文字<font class='ex'>　❙ 自己角色</font>"
    },
    itOther: {
        KR: "아이콘, 글자<font class='ex'>　❙ 타 캐릭터</font>",
        JP: "アイコン、テキスト<font class='ex'>　❙ 他のキャラクター</font>",
        EN: "Icon, Text<font class='ex'>　❙ Other Character</font>",
        FR: "Icône, Text<font class='ex'>　❙ Autre personnage</font>",
        DE: "Symbole, Text<font class='ex'>　❙ Andere Charaktere</font>",
        CN: "图标，文字<font class='ex'>　❙ 其他角色</font>"
    },
    radius: {
        tt: {
            KR: "반경",
            JP: "半径",
            EN: "Radius",
            FR: "Rayon",
            DE: "Radius",
            CN: "半径",
        },
        min: 0,
        max: 50,
        i: "adjust",
        e: "li_slider",
        ul: 1
    },
    TL: {
        tt: {
            KR: "좌상단",
            JP: "左上",
            EN: "Top-Left",
            FR: "Haut-Gauche",
            DE: "Oben-Links",
            CN: "左上",
        },
        i: "looks_one",
        e: "li_checkbox",
        ul: 1
    },
    TR: {
        tt: {
            KR: "우상단",
            JP: "右上",
            EN: "Top-Right",
            FR: "Haut-Droit",
            DE: "Oben-Rechts",
            CN: "右上",
        },
        i: "looks_two",
        e: "li_checkbox",
        ul: 0
    },
    BL: {
        tt: {
            KR: "좌하단",
            JP: "左下",
            EN: "Bottom-Left",
            FR: "Bas-Gauche",
            DE: "Unten-Links",
            CN: "左下",
        },
        i: "looks_3",
        e: "li_checkbox",
        ul: 0
    },
    BR: {
        tt: {
            KR: "우하단",
            JP: "右下",
            EN: "Bottom-Right",
            FR: "Bas-Droit",
            DE: "Unten-Rechts",
            CN: "右下",
        },
        i: "looks_4",
        e: "li_checkbox",
        ul: 0
    },
    direction: {
        left: {
            KR: "왼쪽",
            JP: "左",
            EN: "Left",
            FR: "Gauche",
            DE: "Links",
            CN: "左",
        },
        center: {
            KR: "가운데",
            JP: "真ん中",
            EN: "Center",
            FR: "Centre",
            DE: "Zentriert",
            CN: "居中",
        },
        right: {
            KR: "오른쪽",
            JP: "右",
            EN: "Right",
            FR: "Droite",
            DE: "Rechts",
            CN: "右",
        }
    },
    palette: {
        tt: {
            KR: "팔레트",
            JP: "パレット",
            EN: "Palette",
            FR: "Palette",
            DE: "Palette",
            CN: "调色板",
        },
        m: {
            job: {
                KR: "직업",
                JP: "ジョブ",
                EN: "Job",
                FR: "Job",
                DE: "Job",
                CN: "职业",
            },
            role: {
                KR: "역할",
                JP: "役割",
                EN: "Role",
                FR: "Rôle",
                DE: "Rolle",
                CN: "角色",
            },
            meYou: {
                KR: "내 캐릭터 & 타 캐릭터",
                JP: "自分のキャラクター & 他のキャラクター",
                EN: "My Character & Other Character",
                FR: "Mon personnage & Autre personnage",
                DE: "Eigenen Charakter & Andere Charaktere",
                CN: "自己角色 & 其他角色",
            }
        },
        i: "palette",
        e: "li_radio",
        p: "Design",
        ul: 1,
    },
    myColorUse: {
        tt: {
            KR: "내 캐릭터 색상 적용",
            JP: "自キャラ色の固定",
            EN: "Apply My Character Color",
            FR: "Appliquer la couleur pour mon personnage",
            DE: "Eigene Farbe für eigenen Charakter",
            CN: "固定自己角色的颜色",
        },
        i: "person",
        e: "li_checkbox",
        ul: 1,
    },
    myColor: {
        tt: {
            KR: "내 캐릭터",
            JP: "自分のキャラクター",
            EN: "My Character",
            FR: "Mon personnage",
            DE: "Mein Charakter",
            CN: "自己角色",
        },
        i: "format_color_fill",
        e: "li_color",
        ul: 0
    },
    graph_user: {
        KR: "유저<font class='ex'>　❙ 리미트 브레이크, 초코보 등</font>",
        JP: "ユーザーグ<font class='ex'>　❙ リミットブレイク、チョコボなど</font>",
        EN: "Users<font class='ex'>　❙ Limit Break, Chocobo, etc.</font>",
        FR: "Utilisateur<font class='ex'>　❙ Transcendance, Chocobo, etc.</font>",
        DE: "Benutzer<font class='ex'>　❙ Limitrausch, Chocobo, etc.</font>",
        CN: "用户<font class='ex'>　❙ 极限技，陆行鸟等</font>",
    },
    graph_pet: {
        KR: "소환수<font class='ex'>　❙ 소환수 데이터 합산하기 'ON'</font>",
        JP: "ペット<font class='ex'>　❙ ペットのデータを合算する 'ON'</font>",
        EN: "Pet<font class='ex'>　❙ Combine Pets with Owner 'ON'</font>",
        FR: "Familier<font class='ex'>　❙ Combiner les familiers avec le propriétaire 'ON'</font>",
        DE: "Begleiter<font class='ex'>　❙ Charakter und Begleiter zusammenfassen 'ON'</font>",
        CN: "召唤物<font class='ex'>　❙ 召唤物与自身数据合并 'ON'</font>",
    },
    graph_shield: {
        KR: "D.Shield",
        JP: "D.Shield",
        EN: "D.Shield",
        FR: "D.Shield",
        DE: "D.Shield",
        CN: "D.Shield",
    },
    graph_overheal: {
        KR: "OverHeal",
        JP: "OverHeal",
        EN: "OverHeal",
        FR: "OverHeal",
        DE: "OverHeal",
        CN: "OverHeal",
    },
    LMB: {
        tt: {
            KR: "리미트 브레이크",
            JP: "リミットブレイク",
            EN: "Limit Break",
            FR: "Transcendance",
            DE: "Limitrausch",
            CN: "极限技",
        },
        i: "<img src='./images/icon/frame/LMB.png'/>",
        e: "li_color",
        ul: 1
    },
    CBO: {
        tt: {
            KR: "초코보",
            JP: "チョコボ",
            EN: "Chocobo",
            FR: "Chocobo",
            DE: "Chocobo",
            CN: "陆行鸟",
        },
        i: "<img src='./images/icon/frame/CBO.png'/>",
        e: "li_color",
        ul: 1
    },
    Class: {
        tt: "Job",
        m: {
            KR: "클래스 또는 직업 아이콘",
            JP: "クラスもしくはジョブアイコン",
            EN: "Player\'s class or job icon.",
            FR: "Icône de Classe/Job du joueur",
            DE: "Klassen/Job-Icon des Kämpfers.",
            CN: "玩家职业图标",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    name: {
        tt: "Name",
        m: {
            KR: "캐릭터 이름",
            JP: "キャラ名",
            EN: "The combatant\'s name.",
            FR: "Nom du combatant.",
            DE: "Kämpfername.",
            CN: "角色名称",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    duration: {
        tt: "P.Time",
        m: {
            KR: "전투 로그 수집 시간<br><span class='ac'> = 내 첫 공격 기준</span>",
            JP: "戦闘ログ収集時間<br><span class='ac'> = 自らの攻撃した時点</span>",
            EN: "The duration of the combatant.",
            FR: "Durée du combatant.",
            DE: "Kampfzeit des Charakters.",
            CN: "战斗日志收集时间<br><span class='ac'> = 自己开始攻击时</span>",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    dps: {
        tt: "P.DPS",
        m: {
            KR: "초당 피해량<br><span class='ac'> = P.Time 기준</span>",
            JP: "1秒あたりのダメージ<br><span class='ac'> = P.Time 時点</span>",
            EN: "The damage total of the combatant divided by their personal duration.",
            FR: "Dégâts totaux du combatant divisé par la durée personnelle.",
            DE: "Gesamtschaden der Person dividiert durch die persönliche Kampfzeit.",
            CN: "每秒伤害<br><span class='ac'> = 战斗总伤害除以个人战斗时间</span>",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    EncounterDuration: {
        tt: "Time",
        m: {
            KR: "전투 로그 수집 시간<br><span class='ac'> = 파티 첫 공격 기준</span>",
            JP: "戦闘ログ収集時間<br><span class='ac'> = パティー初めて攻撃した時点</span>",
            EN: "The duration of the encounter.",
            FR: "Durée du combat",
            DE: "Die Kampfzeit.",
            CN: "战斗日志收集时间<br><span class='ac'> = 队伍开始攻击时</span>",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    encdps: {
        tt: "DPS",
        m: {
            KR: "초당 피해량<br><span class='ac'> = Time 기준, 공식</span>",
            JP: "1秒あたりのダメージ<br><span class='ac'> = Time 時点、オフィシャル</span>",
            EN: "The damage total of the combatant divided by the duration of the encounter.<br><span class='ac'> = This is more commonly used than P.DPS</span>",
            FR: "Dégats totaux du combatant divisé par la durée totale du combat.<br><span class='ac'> = Cette option est plus utilisée que le P.DPS</span>",
            DE: "Gesamtschaden dividiert durch die Kampfzeit.<br><span class='ac'> = Diese Option ist weiter verbreitet als P.DPS.</span>",
            CN: "每秒伤害<br><span class='ac'> = 战斗总伤害除以战斗时间</span>",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedLast10DPS: {
        tt: "Last10",
        m: {
            KR: "최근 10초간 평균 DPS",
            JP: "最近10秒間の平均DPS",
            EN: "Average DPS for last 10 seconds.",
            FR: "DPS moyen pour les 10 dernières secondes.",
            DE: "Durchschnittlicher DPS der letzten 10 Sekunden.",
            CN: "最近10秒内的平均DPS",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedLast30DPS: {
        tt: "Last30",
        m: {
            KR: "최근 30초간 평균 DPS",
            JP: "最近30秒間の平均DPS",
            EN: "Average DPS for last 30 seconds.",
            FR: "DPS moyen pour les 30 dernières secondes.",
            DE: "Durchschnittlicher DPS der letzten 30 Sekunden.",
            CN: "最近30秒内的平均DPS",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedLast60DPS: {
        tt: "Last60",
        m: {
            KR: "최근 60초간 평균 DPS",
            JP: "最近60秒間の平均DPS",
            EN: "Average DPS for last 60 seconds.",
            FR: "DPS moyen pour les 60 dernières secondes.",
            DE: "Durchschnittlicher DPS der letzten 60 Sekunden.",
            CN: "最近60秒内的平均DPS",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedLast180DPS: {
        tt: "Last180",
        m: {
            KR: "최근 180초간 평균 DPS",
            JP: "最近180秒間の平均DPS",
            EN: "Average DPS for last 180 seconds.",
            FR: "DPS moyen pour les 180 dernières secondes.",
            DE: "Durchschnittlicher DPS der letzten 180 Sekunden.",
            CN: "最近180秒内的平均DPS",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    damagePct: {
        tt: "D%",
        m: {
            KR: "총 피해량 중 내 캐릭터의 기여율",
            JP: "総ダメージ量の中自キャラの寄與率",
            EN: "This value represents the percent share of all damage done by allies in this encounter.",
            FR: "Pourcentage de dégâts réalisé par rapport au groupe",
            DE: "Prozentualer Anteil am Gesamtschadens der Gruppe.",
            CN: "在总伤害里自己的伤害占比",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedDamage: {
        tt: "Damage",
        m: {
            KR: "피해량",
            JP: "ダメージ量",
            EN: "The amount of damage.",
            FR: "Quantité de dégâts",
            DE: "Summe des verursachten Schadens.",
            CN: "伤害量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedSwings: {
        tt: "Swing",
        m: {
            KR: "공격 횟수<br><span class='ac'> = 자동 공격, 도트, 기술 시전 취소 포함</span>",
            JP: "攻撃回数<br><span class='ac'> = オートアタック、DOT、スキルキャンセル含め</span>",
            EN: "The number of attack attempts.<br><span class='ac'> = This includes any auto-attacks or abilities, also including resisted abilities that do no damage.</span>",
            FR: "Nombre d\'attaques.<br><span class='ac'> = Cela inclu également les auto-attaques et capacités (y compris celles qui ne réalisent pas de dégats.</span>",
            DE: "Ausgeführte Aktionen.<br><span class='ac'> = Umfasst jede Auto-Attacke und Fähigkeit.</span>",
            CN: "攻击次数<br><span class='ac'> = 包含自动攻击，DOT，技能，以及没有伤害的无效攻击。</span>",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    mergedHits: {
        tt: "Hit",
        m: {
            KR: "공격 적중 횟수",
            JP: "攻撃の命中回数",
            EN: "The number of attack attempts that produced damage.",
            FR: "Nombres d\'attaques ayant produit des dégâts.",
            DE: "Ausgeführte Aktionen, welche Schaden verursacht haben.",
            CN: "攻击的命中次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedMisses: {
        tt: "Miss",
        m: {
            KR: "빗나감 횟수",
            JP: "攻撃のミス回数",
            EN: "The number of auto-attacks of CAs that produced a miss message.",
            FR: "Nombres d\'attaques ayant produit le message 'Manqué'.",
            DE: "Anzahl der Auto-Attacken oder Fähigkeiten welche nicht getroffen haben.",
            CN: "攻击的失误次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    hitfailed: {
        tt: "Avoid",
        m: {
            KR: "공격 실패 횟수<br><span class='ac'> = 적의 저항, 반사, 막기, 회피 등</span>",
            JP: "攻撃の失敗回数<br><span class='ac'> = 敵の抵抗、反射、ブロック、回避など</span>",
            EN: "Any type of failed attack that was not a miss.<br><span class='ac'> = This includes resists, reflects, blocks, dodging, etc.</span>",
            FR: "N\'importe quel type d\'attaque échouée mais non manquée.<br><span class='ac'> = Cela inclut les blocages, évitement, résistance, etc.</span>",
            DE: "Anzahl der Attacken, die keinen Schaden verursacht haben, aber kein Miss waren.<br><span class='ac'> = Umfasst: Widerstände, Reflektionen, Ausgeweichen, blocken, usw.</span>",
            CN: "攻击失败次数<br><span class='ac'> = 包括目标的抵抗，反射，阻挡，回避等</span>",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    tohit: {
        tt: "ACC",
        m: {
            KR: "명중률",
            JP: "命中率",
            EN: "The percentage of hits to swings.",
            FR: "Pourcentage de coups portés.",
            DE: "Prozentuale Treffergenauigkeit.",
            CN: "命中率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedDirectHitCount: {
        tt: "D.Hit",
        m: {
            KR: "직격 횟수",
            JP: "ダイレクトヒット回数",
            EN: "The number of hits that were direct hit.",
            FR: "Nombre de coups considérés comme coups nets.",
            DE: "Anzahl der Treffer, die direkt getroffen haben.",
            CN: "直击次数",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    DirectHitPct: {
        tt: "D.HIT",
        m: {
            KR: "직격 발동률",
            JP: "ダイレクトヒット発動率",
            EN: "The percentage of hits that were direct hits.",
            FR: "Pourcentage de coups considérés comme coups nets.",
            DE: "Prozentualer Anteil der Treffer, die direkt getroffen haben.",
            CN: "直击率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedCrithits: {
        tt: "C.Hit",
        m: {
            KR: "공격 극대화 횟수",
            JP: "攻撃のクリティカル回数",
            EN: "The number of damaging attacks that were critical.",
            FR: "Nombres d\'attaques critiques.",
            DE: "Anzahl der kritischen Treffer.",
            CN: "暴击次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    crithitPct: {
        tt: "C.HIT",
        m: {
            KR: "공격 극대화율",
            JP: "攻撃のクリティカル率",
            EN: "The percentage of damaging attacks that were critical.",
            FR: "Pourcentage de coups critiques.",
            DE: "Prozentualer Anteil der kritischen Treffer.",
            CN: "暴击率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedCritDirectHitCount: {
        tt: "C.D.Hit",
        m: {
            KR: "직격 극대화 횟수",
            JP: "ダイレクトヒットクリティカル回数",
            EN: "The number of hits that were critical as well as direct hit.",
            FR: "Nombre de coups considérés comme critiques et coups nets.",
            DE: "Anzahl der Treffer, die direct und kritisch getroffen haben.",
            CN: "直击暴击次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    CritDirectHitPct: {
        tt: "C.D.HIT",
        m: {
            KR: "직격 극대화율",
            JP: "ダイレクトヒットクリティカル率",
            EN: "The percentage of hits that were direct hits as well as critical hits.",
            FR: "Poucentage de coups considérés comme critiques et coups nets.",
            DE: "Prozentualer Anteil der Treffer, die direct und kritisch getroffen haben.",
            CN: "直击暴击率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    maxhit: {
        tt: "MaxHit",
        m: {
            KR: "최대 공격 기술",
            JP: "最大ダメージのスキル",
            EN: "The highest single damaging hit.",
            FR: "Plus forte attaque unique.",
            DE: "Höchster verursachter Schaden durch einen Angriff.",
            CN: "最大伤害技能",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    enchps: {
        tt: "HPS",
        m: {
            KR: "초당 치유량<br><span class='ac'> = Time 기준, 공식</span>",
            JP: "1秒あたりのヒール量<br><span class='ac'> = Time 時点、オフィシャル</span>",
            EN: "The healing total of the combatant divided by the duration of the encounter.",
            FR: "Soins totaux divisés par la durée du combat.",
            DE: "Summe der verursachen Heilung dividiert durch die Kampfzeit.",
            CN: "每秒疗伤<br><span class='ac'> = 治疗总量除以战斗时间</span>",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    healedPct: {
        tt: "H%",
        m: {
            KR: "총 치유량 중 내 캐릭터의 기여율",
            JP: "総ヒール量の中自キャラの寄與率",
            EN: "The value represents the percent share of all healing done by allies in this encounter.",
            FR: "Pourcentage de soins réalisé par rapport au groupe.",
            DE: "Prozentualer Anteil an der gesamten Heilung der Gruppe.",
            CN: "在总治疗量里自己的治疗量占比",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedHealed: {
        tt: "Healed",
        m: {
            KR: "치유량",
            JP: "総ヒール量",
            EN: "The amount of healing.",
            FR: "Quantité de soins.",
            DE: "Summe der verursachten Heilung.",
            CN: "总治疗量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedEffHealed: {
        tt: "Eff.Heal",
        m: {
            KR: "유효 치유량",
            JP: "有効総ヒール量",
            EN: "The amount of healing except for Overheal and D.Shield.",
            FR: "Quantité de soins (overheal et bouclier exclus).",
            DE: "Summe der verursachten Heilung, Overheal und Schilde ausgenommen.",
            CN: "有效治疗量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedDamageShield: {
        tt: "D.Shield",
        m: {
            KR: "보호막의 피해 흡수량",
            JP: "バリアヒール量",
            EN: "The amount of damage blocked by shield abilities of healer.",
            FR: "Quantité de dégâts bloqués par les boucliers du soigneur.",
            DE: "Summe des Schadens, welcher durch Schilde der Healer absorbiert wurde.",
            CN: "治疗防护罩抵消的伤害",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedOverHeal: {
        tt: "OverHeal",
        m: {
            KR: "초과 치유량",
            JP: "オーバーヒール量",
            EN: "The amount of healing that made flood over 100% of health.",
            FR: "Quantité de soins au dessus des HP max de la cible.",
            DE: "Summe der Heilung, welche über 100% Gesundheit verursacht wurde.",
            CN: "无效治疗量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    overHealPct: {
        tt: "OV.H",
        m: {
            KR: "초과 치유율",
            JP: "オーバーヒール率",
            EN: "The percentage of heals above target\'s Max HP.",
            FR: "Poucentage de soins au dessus des HP max de la cible.",
            DE: "Prozentualer Anteil der Heilung, welche über 100% Gesundheit verursacht wurde.",
            CN: "无效治疗占比",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedHeals: {
        tt: "Heal",
        m: {
            KR: "치유 횟수<br><span class='ac'> = 도트, 기술 시전 취소 포함</span>",
            JP: "ヒール回数<br><span class='ac'> = HOT、スキルキャンセル含む</span>",
            EN: "The number of heals from this combatant.",
            FR: "Nombre de soins de ce combatant.",
            DE: "Anzahl der verursachen Heilungen.<br><span class='ac'> = Umfasst auch Heilung von jedem Tick von HoTs wie Regena.</span>",
            CN: "治疗次数<br><span class='ac'> = 包含HOT，技能等</span>",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    mergedCritheals: {
        tt: "C.Heal",
        m: {
            KR: "치유 극대화 횟수",
            JP: "回復のクリティカル回数",
            EN: "The number of heals that were critical.",
            FR: "Nombre de soins critiques.",
            DE: "Anzahl der Heilung, welche kritisch getroffen hat.",
            CN: "治疗暴击次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    crithealPct: {
        tt: "C.HEAL",
        m: {
            KR: "치유 극대화율",
            JP: "回復のクリティカル率",
            EN: "The percentage of heals that were critical.",
            FR: "Pourcentage de soins critiques.",
            DE: "Prozentualer Anteil der Heilung, welche kritisch getroffen hat.",
            CN: "治疗暴击率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    maxheal: {
        tt: "MaxHeal",
        m: {
            KR: "최대 치유 기술",
            JP: "最大回復のスキル",
            EN: "The highest single healing amount.",
            FR: "Plus fort soin unique.",
            DE: "Größte verursachte Heilung.",
            CN: "最大治疗技能",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    mergedDamagetaken: {
        tt: "D.Taken",
        m: {
            KR: "받은 피해량",
            JP: "受けた被ダメージ量",
            EN: "The amount of damage this combatant received.",
            FR: "Quantité de dégâts subit par le combatant.",
            DE: "Summe des erhaltenen Schadens.",
            CN: "承伤量",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    mergedHealstaken: {
        tt: "H.Taken",
        m: {
            KR: "받은 치유량",
            JP: "貰ったヒール量",
            EN: "The amount of healing this combatant received.",
            FR: "Quantité de soins reçue par ce combatant.",
            DE: "Summe der erhaltenen Heilung.",
            CN: "受到治疗量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedAbsorbHeal: {
        tt: "HP",
        m: {
            KR: "기술을 통한 HP 회복량",
            JP: "スキルのよるHP回復量",
            EN: "The amount of power this combatant drained from others.",
            FR: "Quantité de vie absorbée aux autres par ce combatant.",
            DE: "Summe der Lebenspunkte, die durch Kampffähigkeiten regeneriert wurden.",
            CN: "根据技能的HP恢复量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    powerheal: {
        tt: "MP",
        m: {
            KR: "기술을 통한 MP 회복량",
            JP: "スキルのよるMP回復量",
            EN: "The amount of power this combatant replenished to others.",
            FR: "Quantité de mana rendue par ce combatant aux autres.",
            DE: "Summe der Mana, die durch Fähigkeiten regneriert wurde.",
            CN: "根据技能的MP恢复量",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    ParryPct: {
        tt: "PARRY",
        m: {
            KR: "받아넘기기 발동률",
            JP: "受け流し発動率",
            EN: "The percentage of hits that were parried.",
            FR: "Pourcentage de coups parés.",
            DE: "Prozentualer Anteil an parrierten Treffern.",
            CN: "招架率",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    BlockPct: {
        tt: "BLOCK",
        m: {
            KR: "방패막기 발동률",
            JP: "盾ブロック発動率",
            EN: "The percentage of hits that were blocked.",
            FR: "Pourcentage de coups bloqués.",
            DE: "Prozentualer Anteil an geblockten Treffern.",
            CN: "格挡率",
        },
        e: "li_2line_checkbox",
        ul: 0
    },
    mergedCures: {
        tt: "Dispel",
        m: {
            KR: "디버프 해제 기술 시전 횟수",
            JP: "デバフ解除スキルの使用回数",
            EN: "The number of times the combatant dispelled.",
            FR: "Nombre de dispell réalisé par le combatant.",
            DE: "Anzahl der Zauber, welche negative Statuseffekte entfernt haben.",
            CN: "驱散debuff次数",
        },
        e: "li_2line_checkbox",
        ul: 1
    },
    deaths: {
        tt: "Deaths",
        m: {
            KR: "죽음 횟수",
            JP: "死亡回数",
            EN: "The number of times this character was killed by another.",
            FR: "Nombre de mort.",
            DE: "Anzahl der Tode.",
            CN: "死亡次数",
        },
        e: "li_2line_checkbox",
        ul: 0
    }
}
