Mopi2 = {    
    q: {
        keyboard: 1, 
        swap: 0, 
        hideName: 0, 
        pets: 1, 
        dpsType: 0, 
        perType: 1, 
        dmgType: 1, 
        ds: ".", 
        ns: 1, 
        gs: ",", 
        cnt: 1, 
        myName: 0, 
        rank: 0, 
        mhh: 2, 
        mhh_unit: "-", 
        abb: 1, 
        DPS_T: 1, 
        DPS_H: 1,
        DPS_D: 1,
        DPS_C: 1,
        DPS_M: 1,
        HPS_T: 0, 
        HPS_H: 1,
        HPS_D: 0,
        HPS_M: 0,
        HPS_C: 1,
        unit: 1, 
        max_unit: 0, 
        preview: 0, 
        preview24: 0, 
        palette: "job", 
        myColorUse: 0, 
        edgeType: 'solid', 
        rd_navTL: 1, 
        rd_navTR: 1,
        rd_navBL: 1,
        rd_navBR: 1,
        rd_tableTL: 1, 
        rd_tableTR: 1,
        rd_tableBL: 1,
        rd_tableBR: 1,
        applyScope: 3, 
        rd_graphTL: 1, 
        rd_graphTR: 1,
        rd_graphBL: 1,
        rd_graphBR: 1,
        pattern: "cross", 
        iconSet: "glow", 
        btn_Capture: 0, 
        btn_History: 0,
        btn_RequestEnd: 0,
        act: 2, 
        act_rd: 1, 
        act_rh: 1,
        act_md: 0, 
        act_mh: 0,
        act_rank: 1,
        act_max: 1,
        time_italic: 0, 
        target_italic: 0,
        rps_italic: 0,
        header_italic: 0,
        body_italic: 0,
        viewDPS: 1, 
        viewHPS: 1, 
        view24: 1, 
        view24_Number: 10, 
        tableOrder: 1, 
        boldYOU: 1, 
        boldOther: 0, 
        borderTextType: "shadow", 
        ani: 1, 
        gradient: 0, 
        direction: "top", 
        bar_pet: 1,
        bar_ds: 1, 
        bar_oh: 1,
        bar_position: 'right', 
        bar_position_DPS: 'left', 
        arrow: 1, 
        autoHide: 1, 
        tooltips: 1, 
        toast: 1, 
        Lang: "KR", 
        fTime: 'DS-Digital',
        fTarget: 'Segoe UI',
        fRPS: 'Roboto Condensed',
        fHd: 'Roboto Condensed',
        fBody: 'Segoe UI',
        resolution: '62.5%', 
        overlayBg: 0, 
        overlayBgImg: '', 
        overlayBgSize: 'contain', 
        overlayBgRepeat: 'no-repeat', 
        backupDate: 'No Data', 
    },    
    Color: {
        accent: "03A9F4", 
        navBg: "212121", 
        edge: "353535", 
        target: "FFFFFF", 
        rps: "BDBDBD", 
        pattern: "1A1A1A", 
        tableHd: "161616", 
        tableHdText: "BDBDBD", 
        tableBg: "000000", 
        tableYOU: "FFFFFF", 
        tableOther: "FFFFFF", 
        view24TableYOU: "FFFFFF", 
        view24TableOther: "FFFFFF", 
        view24BgYOU: "03A9F4", 
        view24BgOther: "000000", 
        tableLine: "FFFFFF", 
        tableLineVer: "FFFFFF", 
        tableExYOU: "BDBDBD", 
        tableExOther: "BDBDBD", 
        tableBorderYOU: "000000", 
        tableBorderOther: "000000", 
        myColor: "03A9F4", 
        PLD: "7B9AA2",
        WAR: "A91A16",
        DRK: "682531",
        GNB: "796D30",
        WHM: "BDBDBD",
        SCH: "32307B",
        AST: "B1561C",
        ds: "4dd0e1",
        oh: "ef5350",
        MNK: "B38915",
        DRG: "3752D8",
        NIN: "EE2E48",
        SAM: "E45A0F",
        BRD: "ADC551",
        MCH: "148AA9",
        DNC: "E2B0AF",
        BLM: "674598",
        SMN: "32670B",
        RDM: "AC2997",
        BLU: "183D9A",
        LMB: "FFBB00",
        CBO: "757575",
        pet: "000000",
        CRP: "454545",
        BSM: "454545",
        ARM: "454545",
        GSM: "454545",
        LTW: "454545",
        WVR: "454545",
        ALC: "454545",
        CUL: "454545",
        BTN: "303030",
        MIN: "303030",
        FSH: "303030",
        Tanker: "475ECE",
        Healer: "467837",
        DPS: "813B3C",
        Crafter: "454545",
        Gathering: "303030",
        YOU: "607D8B",
        Other: "263238"
    },    
    Range: {
        navTime: 100, 
        navIcon: 100, 
        navBg: 100, 
        edge: 100, 
        target: 100, 
        rps: 100, 
        pattern: 100, 
        tableHd: 100, 
        tableHdText: 100, 
        tableBg: 50, 
        tableYOU: 100, 
        tableOther: 100, 
        tableLine: 10, 
        tableLineVer: 10, 
        view24BgOther: 50,
        view24BgYOU: 50, 
        view24TableYOU: 100, 
        view24TableOther: 100, 
        bar: 75, 
        pet: 50, 
        ds: 75, 
        oh: 75, 
        sizeNav: 42, 
        sizeEdge: 0, 
        sizeRadius: 0, 
        sizeTime: 32, 
        sizeTarget: 12, 
        sizeRPS: 12, 
        sizeGap: 1, 
        sizeIcon: 24, 
        sizePattern: 11, 
        sizeHd: 13, 
        sizeHdText: 11, 
        sizeRadiusTable: 0, 
        sizeBody: 21, 
        sizeBodyText: 12, 
        sizeBodyIcon: 20, 
        sizeLine: 1, 
        sizeLineVer: 0, 
        size24TableSlice: 5, 
        size24TableHeight: 35, 
        size24TableIdxWd: 3, 
        size24BodyIcon: 20, 
        size24BodyNameText: 12, 
        size24BodyDataText: 12, 
        sizeGraph_bar: 21, 
        sizeGraph_pet: 21, 
        sizeGraph_ds: 21, 
        sizeGraph_oh: 21, 
        sizeRadiusGraph: 0, 
        sizeDPSTable: 9, 
        sizeHPSTable: 3, 
        sizeHdGap: 0, 
        sizeDPSGap: 0, 
        sizeHPSGap: 20, 
        autoHideTime: 3, 
    },    
    Alias: {
        "The Forbidden Chakra": "Forb.Chakra",
        "Spineshatter Dive": "Spine.Dive",
        "Midare Setsugekka": "Midare",
        "Hissatsu: Guren": "Guren",
        "Enchanted Redoublement": "E.Redoubl",
        "Enchanted Riposte": "E.Riposte",
        "Enchanted Zwerchhau": "E.Zwerch",
        "Refulgent Arrow": "Ref.Arrow"
    },    
    Order: {
        DPS: ["Class", "name", "encdps", "damagePct", "mergedDamage", "mergedSwings", "DirectHitPct", "crithitPct", "CritDirectHitPct", "maxhit", "deaths"],
        HPS: ["Class", "name", "enchps", "healedPct", "mergedHealed", "mergedEffHealed", "mergedDamageShield", "mergedOverHeal", "overHealPct"]
    },    
    ColData: {
        Class: {
            tt: "Job",
            width: 25,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            class: "Class",
            DPS: 1,
            HPS: 1
        },
        name: {
            tt: "Name",
            width: "100%",
            padding: 0,
            alignHeader: "left",
            alignBody: "left",
            DPS: 1,
            HPS: 1
        },
        duration: {
            tt: "P.Time",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        dps: {
            tt: "P.DPS",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        EncounterDuration: {
            tt: "Time",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        encdps: {
            tt: "DPS",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedLast10DPS: {
            tt: "Last10",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedLast30DPS: {
            tt: "Last30",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedLast60DPS: {
            tt: "Last60",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedLast180DPS: {
            tt: "Last180",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        damagePct: {
            tt: "D%",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedDamage: {
            tt: "Damage",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedSwings: {
            tt: "Swing",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedHits: {
            tt: "Hit",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedMisses: {
            tt: "Miss",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        hitfailed: {
            tt: "Avoid",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        tohit: {
            tt: "ACC",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedDirectHitCount: {
            tt: "D.Hit",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        DirectHitPct: {
            tt: "D.HIT",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedCrithits: {
            tt: "C.Hit",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        crithitPct: {
            tt: "C.HIT",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        mergedCritDirectHitCount: {
            tt: "C.D.Hit",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        CritDirectHitPct: {
            tt: "C.D.HIT",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        },
        maxhit: {
            tt: "MaxHit",
            width: 100,
            padding: 2,
            alignHeader: "left",
            alignBody: "left",
            DPS: 1,
            HPS: 0
        },
        enchps: {
            tt: "HPS",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        healedPct: {
            tt: "H%",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        mergedHealed: {
            tt: "Healed",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        mergedEffHealed: {
            tt: "Eff.Heal",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        mergedDamageShield: {
            tt: "D.Shield",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        mergedOverHeal: {
            tt: "OverHeal",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        overHealPct: {
            tt: "OV.H",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 1
        },
        mergedHeals: {
            tt: "Heal",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedCritheals: {
            tt: "C.Heal",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        crithealPct: {
            tt: "C.HEAL",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        maxheal: {
            tt: "MaxHeal",
            width: 100,
            padding: 2,
            alignHeader: "left",
            alignBody: "left",
            DPS: 0,
            HPS: 0
        },
        mergedDamagetaken: {
            tt: "D.Taken",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedHealstaken: {
            tt: "H.Taken",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedAbsorbHeal: {
            tt: "HP",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        powerheal: {
            tt: "MP",
            width: 50,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        ParryPct: {
            tt: "PARRY",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        BlockPct: {
            tt: "BLOCK",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        mergedCures: {
            tt: "Dispel",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 0,
            HPS: 0
        },
        deaths: {
            tt: "Deaths",
            width: 40,
            padding: 0,
            alignHeader: "center",
            alignBody: "center",
            DPS: 1,
            HPS: 0
        }
    }
}
